"""Stage 3: clean the long table; write processed/interim/gw_clean.parquet and
reports/stage3_cleaning.md.

Run: python scripts/03_clean.py

Checkpoint-1 decisions applied here:
- No total-readings cutoff: every well has >=57 of 92 readings, so all 2,759
  wells are kept (a cutoff would only discard real data).
- The 11 exact-zero readings are flagged (flag_zero), not set to NaN.
"""
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import clean, config  # noqa: E402


def main() -> None:
    long = pd.read_parquet(config.GW_LONG)
    df, log = clean.clean(long)
    df.to_parquet(config.GW_CLEAN, index=False)

    L = ["# Stage 3 cleaning log\n", "_Generated by `scripts/03_clean.py`._\n", "## Counts\n"]
    for k, v in log.items():
        if not k.endswith("_names_changed"):
            L.append(f"- {k}: **{v}**")
    for col in ["state", "district"]:
        ch = log[f"{col}_names_changed"]
        L.append(f"\n## {col.title()} names standardised ({len(ch)} distinct changes)\n")
        L += [f"- `{a}` -> `{b}`" for a, b in ch]
    z = df[df.flag_zero][["well_id", "state", "district", "station_name", "period_label",
                          "season", "well_type", "well_depth_m"]]
    L.append(f"\n## Exact-zero readings ({len(z)}), kept and flagged\n")
    L.append(z.to_markdown(index=False))
    # Context to judge placeholder vs real: the same well's readings that year.
    ctx = (df[df.well_id.isin(z.well_id)]
           .assign(y=lambda d: d.year)
           .merge(z[["well_id", "period_label"]].assign(y=lambda d: d.period_label.str[-2:].astype(int) + 2000),
                  on=["well_id", "y"], suffixes=("", "_zero"))
           .pivot_table(index=["well_id", "y"], columns="season", values="gwl_m_bgl", observed=False))
    L.append("\nSame well, same year, all four rounds (m bgl):\n")
    L.append(ctx.round(2).to_markdown())
    L.append("\n## Extreme flags by season (modified z > 3.5, per well-season; NOT removed)\n")
    L.append(df.groupby("season", observed=True).flag_extreme.sum().to_frame("flagged").to_markdown())
    dw = df[df.flag_deeper_than_well]
    L.append(f"\n## Readings deeper than recorded well depth: {len(dw)} rows in "
             f"{dw.well_id.nunique()} wells\n")
    if len(dw):
        L.append(dw.groupby(["state", "well_type"]).size().to_frame("rows").to_markdown())
        L.append("\nLikely a dry well or a mis-recorded well depth; kept and flagged.")
    (config.REPORTS_DIR / "stage3_cleaning.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
