"""Stage 4b: attach 1/3/6-month antecedent rainfall to every groundwater round.

Run: python scripts/04b_rain_windows.py   (needs stage 3 + 4a outputs)
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import chirps, config, rainfall  # noqa: E402


def main() -> None:
    gw = pd.read_parquet(config.GW_CLEAN)
    rain = pd.read_parquet(config.CHIRPS_TABLE)
    exp = gw.well_id.nunique() * len(chirps.months())
    assert len(rain) == exp, f"CHIRPS table incomplete: {len(rain)} of {exp} rows; rerun 04a"
    out = rainfall.rainfall_windows(gw, rain)   # raises LeakageError on any violation
    out.to_parquet(config.GW_RAIN, index=False)

    L = ["# Stage 4 rainfall integration\n", "_Generated by `scripts/04b_rain_windows.py`._\n",
         f"- CHIRPS v3.0 monthly, {len(chirps.months())} months "
         f"({chirps.FIRST_MONTH} to {chirps.LAST_MONTH}), nearest 0.05 deg cell, HTTPS only.",
         f"- CHIRPS table: {len(rain):,} rows (wells x months); NaN values: {int(rain.precip_mm.isna().sum())}.",
         "- Windows end at month M-1 for an observation in month M; leakage assertion passed for all rows.\n",
         "## Window totals (all rounds)\n",
         out[[f"rain_{w}m_mm" for w in rainfall.WINDOWS]].describe().round(1).to_markdown(),
         "\n## Mean window totals by season (mm)\n",
         out.groupby("season", observed=True)[[f"rain_{w}m_mm" for w in rainfall.WINDOWS]]
            .mean().round(1).to_markdown()]
    (config.REPORTS_DIR / "stage4_rainfall.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
