"""Part C: compare nearest-cell vs 3x3-mean CHIRPS sampling.
Writes reports/chirps_sampling_check.md. Reads both CHIRPS tables, changes neither.

Run: python scripts/04d_chirps_sampling_check.py
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import chirps, config  # noqa: E402

# A well is "large difference" if its mean absolute monthly difference exceeds
# 20% of its mean monthly rainfall, OR its long-run totals differ by > 10%.
# WHY relative: a 10 mm gap is trivial in Kerala (~250 mm/month) but large in Gujarat's dry season.
REL_MAD_FLAG = 0.20
REL_TOTAL_FLAG = 0.10


def main() -> None:
    t3 = pd.read_parquet(chirps.CHIRPS_3X3_TABLE)
    t1 = pd.read_parquet(config.CHIRPS_TABLE)
    cw = pd.read_csv(config.CROSSWALK)
    exp = len(cw) * len(chirps.months())
    assert len(t3) == exp, f"3x3 table incomplete: {len(t3)} of {exp}"
    m = t1.merge(t3, on=["well_id", "year", "month"], validate="one_to_one")
    # The nearest value in the new extraction must reproduce the committed table exactly.
    same = np.isclose(m.precip_mm, m.precip_nearest_mm, equal_nan=True)
    m = m.merge(cw[["well_id", "state", "district", "station_name", "lat", "lon"]], on="well_id")
    m["state"] = m.state.str.title().str.replace("And ", "and ")
    d = m.precip_3x3_mm - m.precip_nearest_mm

    L = ["# CHIRPS sampling check: nearest cell vs 3x3 mean\n",
         "_Generated by `scripts/04d_chirps_sampling_check.py`. The rainfall table used by the "
         "pipeline (`chirps_monthly_by_well.parquet`) is unchanged._\n",
         f"- {len(m):,} well-months ({m.well_id.nunique()} wells x {len(chirps.months())} months, "
         f"{chirps.FIRST_MONTH} to {chirps.LAST_MONTH}).",
         f"- Re-extracted nearest value equals the committed table: **{int(same.sum()):,} / {len(m):,}** "
         f"(max abs diff {np.nanmax(np.abs(m.precip_mm - m.precip_nearest_mm)):.4f} mm).",
         f"- Nearest-cell nodata: **{int(m.precip_nearest_mm.isna().sum())}**; "
         f"3x3 blocks with < 9 valid cells: **{int((m.n_valid_3x3 < 9).sum()):,}** well-months in "
         f"**{m[m.n_valid_3x3 < 9].well_id.nunique()}** wells; all-nodata 3x3: "
         f"**{int(m.precip_3x3_mm.isna().sum())}**.\n",
         "## Agreement (monthly values)\n",
         f"- Pearson r: **{m.precip_nearest_mm.corr(m.precip_3x3_mm):.5f}**",
         f"- Mean absolute difference: **{d.abs().mean():.2f} mm/month** "
         f"(mean monthly rainfall {m.precip_nearest_mm.mean():.1f} mm, so "
         f"{100 * d.abs().mean() / m.precip_nearest_mm.mean():.2f}%)",
         f"- Mean difference (3x3 - nearest): {d.mean():+.3f} mm/month; "
         f"95th / 99th percentile |diff|: {d.abs().quantile(.95):.1f} / {d.abs().quantile(.99):.1f} mm",
         f"- Max |diff|: {d.abs().max():.1f} mm\n"]

    ann = m.groupby(["well_id", "year"]).agg(near=("precip_nearest_mm", "sum"), m3=("precip_3x3_mm", "sum"),
                                             n=("month", "size"))
    ann = ann[ann.n == 12]
    L.append(f"Annual totals (complete calendar years 2000-2022): r = {ann.near.corr(ann.m3):.5f}, "
             f"mean |diff| = {(ann.m3 - ann.near).abs().mean():.1f} mm/yr.\n")

    st = m.assign(diff=d, adiff=d.abs()).groupby("state").agg(
        wells=("well_id", "nunique"), mean_near_mm=("precip_nearest_mm", "mean"),
        mean_diff_mm=("diff", "mean"), mean_abs_diff_mm=("adiff", "mean"),
        r=("precip_nearest_mm", lambda s: s.corr(m.loc[s.index, "precip_3x3_mm"])))
    st["mean_abs_diff_pct"] = 100 * st.mean_abs_diff_mm / st.mean_near_mm
    L += ["## Per state\n", st.round(3).sort_values("mean_abs_diff_pct", ascending=False).to_markdown()]

    pw = m.assign(adiff=d.abs()).groupby("well_id").agg(
        state=("state", "first"), district=("district", "first"), station=("station_name", "first"),
        lat=("lat", "first"), lon=("lon", "first"), mean_near=("precip_nearest_mm", "mean"),
        tot_near=("precip_nearest_mm", "sum"), tot_3x3=("precip_3x3_mm", "sum"),
        mad=("adiff", "mean"), min_valid=("n_valid_3x3", "min"))
    pw["rel_mad"] = pw.mad / pw.mean_near
    pw["rel_total_diff"] = (pw.tot_3x3 - pw.tot_near) / pw.tot_near
    flag = (pw.rel_mad > REL_MAD_FLAG) | (pw.rel_total_diff.abs() > REL_TOTAL_FLAG)
    flagged = pw[flag].sort_values("rel_mad", ascending=False)
    L += [f"\n## Wells with large differences ({len(flagged)} of {len(pw)})\n",
          f"Rule: mean |monthly diff| > {REL_MAD_FLAG:.0%} of the well's mean monthly rainfall, or "
          f"long-run total differs by > {REL_TOTAL_FLAG:.0%}.\n",
          f"Flagged per state: " + ", ".join(f"{k}: {v}" for k, v in flagged.state.value_counts().items()) + "\n",
          flagged.head(40).round(3).to_markdown(),
          "\n(first 40 shown; full list in `reports/chirps_sampling_flagged_wells.csv`)"]
    flagged.to_csv(config.REPORTS_DIR / "chirps_sampling_flagged_wells.csv")
    (config.REPORTS_DIR / "chirps_sampling_check.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
