"""Stage 5: time-aware features; writes processed/interim/gw_features.parquet,
reports/stage5_features.md. (reports/data_quality.md is written by stage 7.)

Run: python scripts/05_features.py
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import config, features as ft  # noqa: E402


def main() -> None:
    df = pd.read_parquet(config.GW_RAIN)
    out = ft.build_features(df, k=ft.K_MAIN, rain=pd.read_parquet(config.CHIRPS_TABLE))
    out.to_parquet(config.GW_FEATURES, index=False)

    r = out[out.gwl_m_bgl.notna()]
    feat_cols = ["n_prior_same_season", "baseline_mean_m", "baseline_std_m", "anomaly_z",
                 "anomaly_z_capped", "trend_5y_m_per_yr"] + [f"rain_{w}m_{s}" for w in (1, 3, 6) for s in ("mm", "dev_mm", "dev_pct")] \
        + ["completeness_to_date", "well_completeness_full_period"]

    L = ["# Stage 5 feature engineering\n", "_Generated by `scripts/05_features.py`._\n",
         f"Feature table: **{out.shape[0]:,} rows x {out.shape[1]} columns** "
         f"({out.well_id.nunique()} wells x {out.period_label.nunique()} rounds).\n",
         "## Columns\n", ", ".join(f"`{c}`" for c in out.columns),
         "\n## Feature summary (rows with a reading)\n",
         r[feat_cols].describe().T.round(3).to_markdown(),
         f"\n- `flag_std_floored` (prior std < {ft.STD_FLOOR_M} m, std floored): "
         f"{int(out.flag_std_floored.sum())} rows",
         f"- |anomaly_z| > 5: {int((r.anomaly_z.abs() > 5).sum())} rows",
         "\n## Sample rows\n",
         out[out.anomaly_z.notna()].sample(6, random_state=1)[
             ["well_id", "period_label", "state", "gwl_m_bgl", "n_prior_same_season", "baseline_mean_m",
              "baseline_std_m", "anomaly_z", "trend_5y_m_per_yr", "rain_3m_mm", "rain_3m_dev_pct",
              "completeness_to_date", "specific_yield"]].round(3).to_markdown(index=False)]
    (config.REPORTS_DIR / "stage5_features.md").write_text("\n".join(L) + "\n")

    print("\n".join(L))


if __name__ == "__main__":
    main()
