"""Stage 5: time-aware features; writes processed/interim/gw_features.parquet,
reports/stage5_features.md and the stage-5 sections of reports/data_quality.md.

Run: python scripts/05_features.py
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import config, features as ft  # noqa: E402


def availability_table(df: pd.DataFrame) -> pd.DataFrame:
    """% of wells with a reading, season x year."""
    t = df.pivot_table(index="season", columns="year", values="gwl_m_bgl",
                       aggfunc=lambda s: round(100 * s.notna().mean(), 1), observed=False)
    return t


def main() -> None:
    df = pd.read_parquet(config.GW_RAIN)
    out = ft.build_features(df, k=ft.K_MAIN)
    out.to_parquet(config.GW_FEATURES, index=False)

    sens = ft.k_sensitivity(out)
    r = out[out.gwl_m_bgl.notna()]
    by_season = pd.DataFrame({f"K={k}": r.assign(x=r.n_prior_same_season < k)
                              .groupby("season", observed=True).x.sum() for k in ft.K_SENSITIVITY})
    feat_cols = ["n_prior_same_season", "baseline_mean_m", "baseline_std_m", "anomaly_z",
                 "trend_5y_m_per_yr"] + [f"rain_{w}m_{s}" for w in (1, 3, 6) for s in ("mm", "dev_mm", "dev_pct")] \
        + ["completeness_to_date", "well_completeness_full_period"]

    L = ["# Stage 5 feature engineering\n", "_Generated by `scripts/05_features.py`._\n",
         f"Feature table: **{out.shape[0]:,} rows x {out.shape[1]} columns** "
         f"({out.well_id.nunique()} wells x {out.period_label.nunique()} rounds).\n",
         "## Columns\n", ", ".join(f"`{c}`" for c in out.columns),
         "\n## Feature summary (rows with a reading)\n",
         r[feat_cols].describe().T.round(3).to_markdown(),
         f"\n- `flag_std_floored` (prior std < {ft.STD_FLOOR_M} m, std floored): "
         f"{int(out.flag_std_floored.sum())} rows",
         f"- |anomaly_z| > 5: {int((r.anomaly_z.abs() > 5).sum())} rows",
         "\n## Sample rows\n",
         out[out.anomaly_z.notna()].sample(6, random_state=1)[
             ["well_id", "period_label", "state", "gwl_m_bgl", "n_prior_same_season", "baseline_mean_m",
              "baseline_std_m", "anomaly_z", "trend_5y_m_per_yr", "rain_3m_mm", "rain_3m_dev_pct",
              "completeness_to_date", "specific_yield"]].round(3).to_markdown(index=False)]
    (config.REPORTS_DIR / "stage5_features.md").write_text("\n".join(L) + "\n")

    # data_quality.md: sections available after stage 5; stage 7 completes it.
    av = availability_table(out)
    D = ["# Data quality report\n",
         "_Generated by `scripts/05_features.py` (stage 5). Stage 7 adds final counts, "
         "stress categories and the partitioned output._\n",
         "## Season x year availability (% of 2,759 wells with a reading)\n",
         av.to_markdown(),
         "\n**Heavily missing cells** (an empty round means no baseline update and no "
         "anomaly for that round):\n"]
    for season, year in [("pre_monsoon", 2020), ("pre_monsoon", 2021), ("monsoon", 2012),
                         ("post_monsoon_rabi", 2016)]:
        D.append(f"- {season} {year}: **{av.loc[season, year]}%** of wells measured")
    low = av.stack()
    low = low[low < 70].sort_values()
    D.append("\nAll season-years below 70%: " + ", ".join(f"{s} {y} ({v}%)" for (s, y), v in low.items()))
    D += [f"\n## Minimum-history rule (main K = {ft.K_MAIN}; K = 3 and 8 for sensitivity)\n",
          "A baseline, anomaly and stress category need at least K earlier readings "
          "of the same well in the same season.\n",
          sens.to_markdown(index=False),
          "\nReadings excluded per season:\n", by_season.to_markdown(),
          "\nThe 444 wells with no May series contribute all of their May rows to "
          "'Insufficient history' at every K; their other seasons are kept."]
    (config.REPORTS_DIR / "data_quality.md").write_text("\n".join(D) + "\n")
    print("\n".join(L + [""] + D))


if __name__ == "__main__":
    main()
