"""Stage 6: stress classification + threshold sensitivity.
Writes processed/interim/gw_stress.parquet and reports/stage6_stress.md.

Run: python scripts/06_stress.py
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import config, stress, validity  # noqa: E402


def main() -> None:
    df = pd.read_parquet(config.GW_FEATURES)
    df["stress_category"] = stress.classify(df["gwl_m_bgl"], df["anomaly_z"])
    # Identity check promised in the docs: capped z gives the same labels.
    assert (stress.classify(df["gwl_m_bgl"], df["anomaly_z_capped"]) == df["stress_category"]).all()
    # Part B: the same classify() on the rolling-baseline anomaly. Existing stress
    # columns are untouched; stress_category remains the primary label.
    df["stress_roll10"] = stress.classify(df["gwl_m_bgl"], df["anomaly_roll10"])
    assert (stress.classify(df["gwl_m_bgl"], df["anomaly_roll10_capped"]) == df["stress_roll10"]).all()
    df = validity.suspect_flags(df)   # Part D: descriptive QC flag, nothing removed
    df.to_parquet(config.GW_STRESS, index=False)

    counts, changes = stress.sensitivity(df)
    by_season = pd.crosstab(df["season"], df["stress_category"])
    L = ["# Stage 6 stress classification\n", "_Generated by `scripts/06_stress.py`._\n",
         "Default thresholds (1, 1.5, 2) SD on the positive (deeper-than-usual) anomaly; "
         "negative anomalies are Normal. Precedence: No reading > Insufficient history > z bands.\n",
         "## Category counts under each threshold set\n", counts.to_markdown(),
         "\n## Rows changing category relative to the default set\n",
         changes.to_markdown(index=False),
         "\n'% of classified rows' excludes No reading / Insufficient history, which no threshold changes.",
         "\n## Default categories by season\n", by_season.to_markdown()]
    (config.REPORTS_DIR / "stage6_stress.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
