"""Stage 7: final partitioned Parquet + reports/data_quality.md.

Run: python scripts/07_output.py   (needs stage 6 output)

PARTITIONING CHOICE: by state (19 partitions), not by year (23).
WHY:
- The project's core test is cross-REGION generalisation: train on some
  states, test on held-out states. With state partitions a leave-one-state-out
  split reads whole directories; a year layout would force every split to
  scan all 23 partitions.
- The dashboard filters by state first.
- Size: the whole table is a few MB per state, so partitions are neither tiny
  nor large. Year partitions would also not help temporal splits much: every
  temporal feature already carries `year`, and the full table loads in < 1 s.
"""
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import config, features as ft, stress  # noqa: E402

MAX_COMMIT_MB = 50


def dir_size_mb(p: Path) -> float:
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file()) / 1e6


def main() -> None:
    df = pd.read_parquet(config.GW_STRESS)
    df = df.sort_values(["state", "well_id", "date"]).reset_index(drop=True)

    if config.FINAL_DIR.exists():
        shutil.rmtree(config.FINAL_DIR)   # never mix files from an older run
    # Partition on a filesystem-safe slug ("andhra_pradesh") rather than the
    # display name: pyarrow URL-encodes spaces in directory names
    # ("state=Andhra%20Pradesh"), which is awkward for other tools. `state`
    # stays an ordinary column inside every file.
    df["state_slug"] = df["state"].str.lower().str.replace(r"[^a-z0-9]+", "_", regex=True)
    df.to_parquet(config.FINAL_DIR, partition_cols=["state_slug"], index=False)
    size = dir_size_mb(config.FINAL_DIR)
    biggest = max(f.stat().st_size for f in config.FINAL_DIR.rglob("*.parquet")) / 1e6
    assert biggest < MAX_COMMIT_MB, "a partition exceeds the commit limit; commit a sample instead"
    back = pd.read_parquet(config.FINAL_DIR)
    assert len(back) == len(df) and back.well_id.nunique() == df.well_id.nunique()
    assert back.state.nunique() == 19

    raw = pd.read_parquet(config.GW_LONG)
    r = df[df.gwl_m_bgl.notna()]
    D: list[str] = []
    w = D.append

    w("# Data quality report\n")
    w("_Generated by `scripts/07_output.py`. Do not edit by hand; rerun the pipeline._\n")
    w("Source: Figshare 10.6084/m9.figshare.29293877.v3, "
      "`Output/CGWB_India_filtered_GWLs_ref_sy_2000_2022.csv` (CC BY 4.0); "
      "rainfall: CHIRPS v3.0 monthly (Climate Hazards Center).\n")

    w("## 1. Final table\n")
    w(f"- Rows: **{len(df):,}** (one per well x monitoring round; {df.period_label.nunique()} rounds, "
      "Jan/May/Aug/Nov 2000-2022)")
    w(f"- Rows with a reading: **{len(r):,}**")
    w(f"- Wells: **{df.well_id.nunique():,}**; states: **{df.state.nunique()}**; "
      f"districts: **{df.groupby(['state', 'district']).ngroups}**")
    w(f"- Columns: {df.shape[1]}. Output: `processed/{config.FINAL_DIR.name}/state_slug=<state>/` "
      f"({size:.1f} MB in total, largest file {biggest:.1f} MB; partitioned by state, see "
      "`scripts/07_output.py` for why)\n")
    cov = df.groupby("state").agg(wells=("well_id", "nunique"), districts=("district", "nunique"),
                                  readings=("gwl_m_bgl", "count"))
    cov["readings_per_well"] = (cov.readings / cov.wells).round(1)
    w("### Coverage by state\n")
    w(cov.to_markdown())

    w("\n## 2. Wells dropped\n")
    w("**None.** Every well has at least 57 of 92 readings, so no total-readings cutoff "
      "was applied (checkpoint-1 decision). Wells with no May series are kept; their "
      "May rounds are labelled `No reading`.\n")
    w("Upstream (authors' QC, not repeated here): wells with no data, wells with any "
      "negative value, readings outside 3 sigma, wells with < 2 readings in any year "
      "2000-2022, and wells with a value repeated > 2 times in a row were removed by the "
      "dataset authors before this table. See `src/gwstress/clean.py`.\n")

    w("## 3. Missingness before and after cleaning\n")
    mb, ma = raw.gwl_m_bgl.isna().mean(), df.gwl_m_bgl.isna().mean()
    w(f"| | rows | readings | missing % |\n|---|---:|---:|---:|\n"
      f"| before cleaning (stage 2) | {len(raw):,} | {raw.gwl_m_bgl.notna().sum():,} | {100 * mb:.2f} |\n"
      f"| after cleaning (final) | {len(df):,} | {df.gwl_m_bgl.notna().sum():,} | {100 * ma:.2f} |\n")
    w("Identical by design: cleaning found no placeholders and no duplicates, and "
      "removes nothing else (zeros and extremes are flagged, not dropped).\n")
    miss = df.groupby("season", observed=True).gwl_m_bgl.apply(lambda s: round(100 * s.isna().mean(), 2))
    w("Missing % by season:\n")
    w(miss.to_frame("missing_%").to_markdown())

    w("\n## 4. Season x year availability (% of 2,759 wells with a reading)\n")
    av = df.pivot_table(index="season", columns="year", values="gwl_m_bgl",
                        aggfunc=lambda s: round(100 * s.notna().mean(), 1), observed=False)
    w(av.to_markdown())
    w("\n**Heavily missing rounds:**\n")
    for s, y in [("pre_monsoon", 2020), ("pre_monsoon", 2021), ("monsoon", 2012),
                 ("post_monsoon_rabi", 2016)]:
        w(f"- {s} {y}: **{av.loc[s, y]}%** of wells measured")
    low = av.stack()
    low = low[low < 70].sort_values()
    w("\nAll season-years below 70%: " + ", ".join(f"{s} {y} ({v}%)" for (s, y), v in low.items()) + ".")
    nos = df[df.well_has_no_series_for_season].groupby(["season", "state"], observed=True).well_id.nunique()
    w(f"\nWells with no readings at all for a season (`well_has_no_series_for_season`): "
      + ", ".join(f"{s} / {st}: {n}" for (s, st), n in nos.items()) + ".")

    w("\n## 5. Flags (kept, not removed)\n")
    fl = {c: int(df[c].sum()) for c in ["flag_zero", "flag_extreme", "flag_negative",
                                        "flag_deeper_than_well", "flag_std_floored"]}
    w("| flag | rows | meaning |\n|---|---:|---|")
    meaning = {"flag_zero": "reading exactly 0.0 m (water at surface or placeholder)",
               "flag_extreme": "modified z > 3.5 within well-season (descriptive; uses whole record)",
               "flag_negative": "negative depth (other datum / artesian)",
               "flag_deeper_than_well": "deeper than recorded well depth (dry well or bad depth)",
               "flag_std_floored": f"prior same-season std < {ft.STD_FLOOR_M} m; std floored"}
    for k, v in fl.items():
        w(f"| `{k}` | {v:,} | {meaning[k]} |")
    w("\nThe 11 zero readings are listed with context in `reports/stage3_cleaning.md`. Three look "
      "suspicious and are kept flagged only: `Waf941bb407` (Ujjain, Aug-19: 17.5/16.6 -> 0 -> 4.7 m), "
      "`W50b118a710` (Raisen, Nov-19: 8.2 m in May -> 0), `W9934cc4de3` (Nellore, Jan-18).")
    w(f"\n|anomaly_z| > {ft.Z_CAP:g}: **{int((r.anomaly_z.abs() > ft.Z_CAP).sum()):,}** rows "
      f"(raw range {r.anomaly_z.min():.1f} to {r.anomaly_z.max():.1f}). Raw `anomaly_z` is kept "
      f"unchanged; **models should use `anomaly_z_capped`** (clipped to +/-{ft.Z_CAP:g}).")

    w(f"\n## 6. Minimum-history rule (main K = {ft.K_MAIN}; K = 3, 8 as sensitivity)\n")
    w("A baseline / anomaly / stress category needs at least K earlier readings of the "
      "same well in the same season. Counts are over rounds WITH a reading.\n")
    w(ft.k_sensitivity(df).to_markdown(index=False))
    by_season = pd.DataFrame({f"excluded K={k}": r.assign(x=r.n_prior_same_season < k)
                              .groupby("season", observed=True).x.sum() for k in ft.K_SENSITIVITY})
    w("\nExcluded readings per season:\n")
    w(by_season.to_markdown())
    w("\nExclusions are essentially each well-season's first K readings, so they fall on the "
      "early years (2000-2004 at K=5).")

    w("\n## 7. Trend availability\n")
    tr_nan = r.trend_5y_m_per_yr.isna()
    may22 = r[(r.season == "pre_monsoon") & (r.year == 2022)]
    w(f"- Readings with no trend (fewer than {ft.TREND_MIN_POINTS} of the prior {ft.TREND_YEARS} "
      f"same-season readings): **{int(tr_nan.sum()):,}** of {len(r):,}.")
    w(f"- May 2022 readings with no trend: **{int(may22.trend_5y_m_per_yr.isna().sum()):,}** of "
      f"{len(may22):,} (May 2020/2021 are almost empty, so 4-of-5 cannot be met). The rule "
      "is deliberately not loosened.")

    w("\n## 8. Stress categories (default thresholds 1 / 1.5 / 2 SD)\n")
    cc = df.stress_category.value_counts().reindex(stress.CATEGORIES)
    w(pd.DataFrame({"rows": cc, "% of all rows": (100 * cc / len(df)).round(2)}).to_markdown())
    classified = df[~df.stress_category.isin([stress.NO_READING, stress.INSUFFICIENT])]
    hs = (classified.stress_category == "High Stress").mean()
    w(f"\nHigh Stress is {100 * hs:.1f}% of classified rows, versus 2.3% expected if z were standard "
      "normal. Expected rather than a bug: an expanding baseline lags a declining water table, so "
      "later readings in declining wells sit persistently above it.")
    counts, changes = stress.sensitivity(df)
    w("\n### Threshold sensitivity\n")
    w(counts.to_markdown())
    w("\n")
    w(changes.to_markdown(index=False))
    w("\n### Default categories by state (% of classified rows)\n")
    st = pd.crosstab(classified.state, classified.stress_category.astype(str), normalize="index")
    w((100 * st[["Normal", "Watch", "Moderate Stress", "High Stress"]]).round(1).to_markdown())

    w("\n## 9. Expanding vs rolling (10-reading) baseline\n")
    w("`stress_category` uses the expanding baseline (all earlier same-season readings, K=5). "
      "`stress_roll10` uses the last 10 earlier same-season readings (minimum 5), with the same "
      "0.10 m floor, the same thresholds and the same classify(). The primary label is still "
      "`stress_category`.\n")
    cmp = pd.DataFrame({"expanding (stress_category)": df.stress_category.value_counts(),
                        "rolling (stress_roll10)": df.stress_roll10.value_counts()}).reindex(stress.CATEGORIES)
    w(cmp.to_markdown())
    both = df[~df.stress_category.isin([stress.NO_READING, stress.INSUFFICIENT])
              & ~df.stress_roll10.isin([stress.NO_READING, stress.INSUFFICIENT])]
    hs_e = (both.stress_category == "High Stress").mean()
    hs_r = (both.stress_roll10 == "High Stress").mean()
    w(f"\nOn the {len(both):,} readings classified under BOTH baselines, High Stress is "
      f"**{100 * hs_e:.2f}%** (expanding) vs **{100 * hs_r:.2f}%** (rolling); 2.28% expected under a "
      "standard normal.")
    rc = df[df.gwl_m_bgl.notna()]
    changed = (rc.stress_category.astype(str) != rc.stress_roll10.astype(str))
    w(f"\nReadings whose category differs between the two: **{int(changed.sum()):,}** of {len(rc):,} "
      f"({100 * changed.mean():.1f}%); among readings classified under both: "
      f"**{int((both.stress_category.astype(str) != both.stress_roll10.astype(str)).sum()):,}** "
      f"({100 * (both.stress_category.astype(str) != both.stress_roll10.astype(str)).mean():.1f}%).\n")
    w("Transition matrix (rows: expanding, columns: rolling), readings only:\n")
    w(pd.crosstab(rc.stress_category.astype(str), rc.stress_roll10.astype(str))
      .reindex(index=stress.CATEGORIES[1:], columns=stress.CATEGORIES[1:]).fillna(0).astype(int).to_markdown())
    hs_state = both.groupby("state").agg(
        expanding_high_pct=("stress_category", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        rolling_high_pct=("stress_roll10", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        readings=("well_id", "size"))
    w("\nHigh Stress rate per state (readings classified under both):\n")
    w(hs_state.to_markdown())
    by_year = both.groupby("year").agg(
        expanding=("stress_category", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        rolling=("stress_roll10", lambda s: round(100 * (s == "High Stress").mean(), 2)))
    w("\nHigh Stress rate per year (%):\n")
    w(by_year.T.to_markdown())

    from scipy import stats as sps
    w("\n### Why High Stress exceeds 2.3%: small-sample std, not baseline lag\n")
    w("If the readings in a well-season were independent Gaussian draws, a z-score using the mean "
      "and std of only n earlier readings follows a scaled t-distribution, not a standard normal. "
      "So P(z >= 2) is well above 2.28% when n is small. Observed vs that expectation, by number of "
      "earlier readings (expanding baseline):\n")
    cls = df[~df.stress_category.isin([stress.NO_READING, stress.INSUFFICIENT])]
    bins = pd.cut(cls.n_prior_same_season, [4, 7, 10, 14, 18, 22])
    obs = cls.groupby(bins, observed=True).stress_category.apply(lambda s: 100 * (s == "High Stress").mean())
    exp = [100 * np.mean([sps.t.sf(2 * np.sqrt(n / (n + 1)), n - 1) for n in range(iv.left + 1, iv.right + 1)])
           for iv in obs.index]
    w(pd.DataFrame({"earlier readings": [str(i) for i in obs.index], "observed High %": obs.round(2).values,
                    "expected if i.i.d. Gaussian %": np.round(exp, 2),
                    "readings": cls.groupby(bins, observed=True).size().values}).to_markdown(index=False))
    w("\nThe rest of the gap lines up with known drought years (High Stress peaks in 2009 and "
      "2015-2018 in the per-year table above). The rolling baseline does not reduce the rate. It "
      "raises it slightly (more rows sit at small n, and recent-decade std is smaller), so baseline "
      "lag is not the main cause. A steady LINEAR decline does not inflate the expanding z either: "
      "the mean lags, but the std grows at the same rate, so z settles near a constant (about 1.7).")

    w("\n## 10. Small-sample-adjusted anomaly (`stress_tadj`) vs `stress_category`\n")
    w("`anomaly_tadj` maps (x - mean) / (s * sqrt(1 + 1/n)) through the Student-t CDF with n - 1 "
      "degrees of freedom, then the inverse normal CDF. Under i.i.d. Gaussian readings it has nominal "
      "normal tails at every n (Monte Carlo test in `tests/test_features.py`). Same K = 5, 0.10 m "
      "floor, thresholds and labels. `stress_category` stays the primary label.\n")
    cls2 = df[~df.stress_category.isin([stress.NO_READING, stress.INSUFFICIENT])]
    def rates(col, d=cls2):
        return pd.Series({c: round(100 * (d[col] == c).mean(), 2)
                          for c in ["Normal", "Watch", "Moderate Stress", "High Stress"]})
    w(pd.DataFrame({"stress_category %": rates("stress_category"), "stress_tadj %": rates("stress_tadj"),
                    "nominal if Gaussian %": [round(100 * sps.norm.cdf(1), 2),
                                              round(100 * (sps.norm.cdf(1.5) - sps.norm.cdf(1)), 2),
                                              round(100 * (sps.norm.cdf(2) - sps.norm.cdf(1.5)), 2),
                                              round(100 * sps.norm.sf(2), 2)]}).to_markdown())
    hs0, hs1, hsn = (100 * (cls2.stress_category == "High Stress").mean(),
                     100 * (cls2.stress_tadj == "High Stress").mean(), 100 * sps.norm.sf(2))
    w(f"\nExcess High Stress over the nominal {hsn:.2f}%: {hs0 - hsn:.2f} points (expanding) -> "
      f"{hs1 - hsn:.2f} points (t-adjusted), i.e. **{100 * (1 - (hs1 - hsn) / (hs0 - hsn)):.0f}% of the "
      "excess disappears** once small-sample uncertainty is accounted for.")
    ch = (cls2.stress_category.astype(str) != cls2.stress_tadj.astype(str))
    w(f"\nReadings that change category: **{int(ch.sum()):,}** of {len(cls2):,} classified "
      f"({100 * ch.mean():.1f}%). The adjustment only shrinks |z| (t tails are heavier, and "
      "sqrt(1 + 1/n) > 1), so every change moves one or more steps towards Normal.\n")
    w(pd.crosstab(cls2.stress_category.astype(str), cls2.stress_tadj.astype(str))
      .reindex(index=stress.CATEGORIES[2:], columns=stress.CATEGORIES[2:]).fillna(0).astype(int).to_markdown())
    yr = cls2.groupby("year").agg(
        high_expanding=("stress_category", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        high_tadj=("stress_tadj", lambda s: round(100 * (s == "High Stress").mean(), 2)))
    w("\nHigh Stress rate per year (%):\n")
    w(yr.T.to_markdown())
    stt = cls2.groupby("state").agg(
        high_expanding=("stress_category", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        high_tadj=("stress_tadj", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        moderate_tadj=("stress_tadj", lambda s: round(100 * (s == "Moderate Stress").mean(), 2)),
        watch_tadj=("stress_tadj", lambda s: round(100 * (s == "Watch").mean(), 2)),
        readings=("well_id", "size"))
    w("\nBy state (%):\n")
    w(stt.to_markdown())
    nb = pd.cut(cls2.n_prior_same_season, [4, 7, 10, 14, 18, 22])
    w("\nHigh Stress by number of earlier readings (%):\n")
    w(cls2.groupby(nb, observed=True).agg(
        expanding=("stress_category", lambda s: round(100 * (s == "High Stress").mean(), 2)),
        tadj=("stress_tadj", lambda s: round(100 * (s == "High Stress").mean(), 2)))
      .rename(index=str).to_markdown())
    w(f"\n**What remains.** After adjustment, High Stress is {hs1:.2f}% vs {hsn:.2f}% nominal. The "
      "remaining excess is concentrated in particular years (see the per-year row), consistent with "
      "drought-driven declines (e.g. the deficient 2009 and 2014-2015 monsoons). It also reflects that "
      "real readings are neither independent nor Gaussian (serial correlation, trends, heavy tails), "
      "which the t-adjustment does not model. This report does not attribute the remainder to any "
      "single cause.")

    (config.REPORTS_DIR / "data_quality.md").write_text("\n".join(D) + "\n")
    print("\n".join(D))
    print(f"\nwrote {config.FINAL_DIR} ({size:.1f} MB)")


if __name__ == "__main__":
    main()
