"""Part D: data-validity checks -> reports/data_validity.md. Changes no data.

Run: python scripts/08_validity.py   (after stage 7 and Part C)
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import chirps, config, validity  # noqa: E402

# Long-run monsoon (JJAS) mean below this, for a whole state or a single well,
# is implausible anywhere in the 19 states covered (the driest, Gujarat's
# Kutch/Saurashtra, gets ~300-400 mm). Per well-year, < 50 mm JJAS only happens
# in severe droughts in arid west India, so those are listed for review, not "wrong".
STATE_MONSOON_MIN_MM = 300
WELL_MONSOON_MIN_MM = 150
WELLYEAR_MONSOON_MIN_MM = 50
ANNUAL_MAX_MM = 7000  # above the wettest stations in the covered states (coastal Karnataka/Kerala ~4-5 m)


def main() -> None:
    df = pd.read_parquet(config.FINAL_DIR)
    cw = pd.read_csv(config.CROSSWALK)
    wells = df.groupby("well_id").agg(lat=("lat", "first"), lon=("lon", "first"), state=("state", "first"),
                                      district=("district", "first"), station=("station_name", "first")).reset_index()
    L = ["# Data validity checks\n", "_Generated by `scripts/08_validity.py`. No reading is deleted or changed._\n"]

    # 1. Coordinates
    cc = validity.coordinate_checks(wells)
    b = config.INDIA_BBOX
    L += ["## 1. Coordinates\n",
          f"- Bounding box: lat {b['lat_min']}-{b['lat_max']}, lon {b['lon_min']}-{b['lon_max']}. "
          f"Wells outside: **{len(cc['outside_bbox'])}**.",
          f"- Observed extent: lat {wells.lat.min():.4f}-{wells.lat.max():.4f}, "
          f"lon {wells.lon.min():.4f}-{wells.lon.max():.4f}."]
    rain = pd.read_parquet(config.CHIRPS_TABLE)
    nod = rain[rain.precip_mm.isna()].well_id.nunique()
    L.append(f"- Wells whose nearest CHIRPS cell is nodata in any month: **{nod}** "
             f"({int(rain.precip_mm.isna().sum())} NaN values in {len(rain):,}).")
    if chirps.CHIRPS_3X3_TABLE.exists():
        t3 = pd.read_parquet(chirps.CHIRPS_3X3_TABLE)
        part = t3[t3.n_valid_3x3 < 9]
        L.append(f"- Wells with any nodata cell in the 3x3 neighbourhood (coast/edge proxy): "
                 f"**{part.well_id.nunique()}**.")
    co = cc["colocated"]
    grp = co.groupby(["lat", "lon"])
    L.append(f"- Co-located wells (identical lat/lon): **{len(co)} wells at {grp.ngroups} locations** "
             f"(group sizes: {grp.size().value_counts().sort_index().to_dict()}).")
    if len(co):
        L += ["\nCo-located wells:\n", co[["lat", "lon", "well_id", "state", "district", "station"]]
              .to_markdown(index=False),
              "\nCo-located wells share every rainfall value (same CHIRPS cell). They are separate "
              "monitoring points (different station names), so they are kept. For cross-validation, "
              "the state-level split already keeps them together."]
    near = wells[["lat", "lon"]].round(3).duplicated(keep=False).sum()
    L.append(f"\nWells sharing coordinates when rounded to 0.001 deg (~110 m): {near}.")

    # 2. Suspect readings
    s = df[df.suspect_reading]
    reasons = s.suspect_reason.str.split(";").explode()
    L += ["\n## 2. Suspect readings (`suspect_reading`, `suspect_reason`)\n",
          "Composite descriptive flag. Reasons: `zero_suspicious` (the 3 zero readings judged "
          "implausible: " + ", ".join(f"{w} {p}" for w, p in config.SUSPICIOUS_ZEROS) + "), "
          "`deeper_than_well` (reading deeper than recorded well depth), `extreme_anomaly` "
          f"(|anomaly_z| > {validity.EXTREME_Z:g}, past-only baseline). Values are unchanged.\n",
          f"- Flagged readings: **{len(s):,}** of {int(df.gwl_m_bgl.notna().sum()):,} "
          f"({100 * len(s) / df.gwl_m_bgl.notna().sum():.2f}%) in **{s.well_id.nunique()}** wells.\n",
          "Per reason (a reading can have two):\n",
          reasons.value_counts().to_frame("readings").to_markdown(),
          "\nPer reason combination:\n", s.suspect_reason.value_counts().to_frame("readings").to_markdown(),
          "\nPer state (a reading with two reasons is counted once, under its first reason; "
          "the 17 `deeper_than_well;extreme_anomaly` readings appear under deeper_than_well):\n",
          pd.crosstab(df[df.suspect_reading].state, reasons.groupby(level=0).first().reindex(s.index).values)
          .assign(total_flagged=s.groupby("state").size())
          .join(df[df.gwl_m_bgl.notna()].groupby("state").size().rename("readings"))
          .assign(pct=lambda t: (100 * t.total_flagged / t.readings).round(2)).to_markdown()]
    top = s.groupby("well_id").size().sort_values(ascending=False).head(10)
    L += ["\nWells with the most suspect readings:\n",
          top.to_frame("suspect").join(wells.set_index("well_id")[["state", "district", "station"]]).to_markdown()]

    # 3. Rainfall plausibility
    r = rain.merge(wells[["well_id", "state"]], on="well_id")
    full = r[r.year.between(2000, 2022)]
    annual = full.groupby(["well_id", "state", "year"]).precip_mm.sum().reset_index()
    jjas = full[full.month.between(6, 9)].groupby(["well_id", "state", "year"]).precip_mm.sum().reset_index()
    st = pd.DataFrame({"mean_annual_mm": annual.groupby("state").precip_mm.mean(),
                       "mean_monsoon_JJAS_mm": jjas.groupby("state").precip_mm.mean(),
                       "min_well_mean_monsoon_mm": jjas.groupby(["state", "well_id"]).precip_mm.mean()
                       .groupby("state").min(),
                       "max_well_mean_annual_mm": annual.groupby(["state", "well_id"]).precip_mm.mean()
                       .groupby("state").max()})
    st["monsoon_share_pct"] = 100 * st.mean_monsoon_JJAS_mm / st.mean_annual_mm
    st["flag"] = np.where(st.mean_monsoon_JJAS_mm < STATE_MONSOON_MIN_MM, "LOW MONSOON", "")
    L += ["\n## 3. Rainfall plausibility (CHIRPS nearest cell, calendar years 2000-2022)\n",
          st.round(1).to_markdown()]
    wm = jjas.groupby(["well_id", "state"]).precip_mm.mean()
    low_w = wm[wm < WELL_MONSOON_MIN_MM]
    wy_low = jjas[jjas.precip_mm < WELLYEAR_MONSOON_MIN_MM]
    wa = annual.groupby("well_id").precip_mm.mean()
    L += [f"\n- States with mean monsoon < {STATE_MONSOON_MIN_MM} mm: "
          f"**{int((st.flag != '').sum())}**.",
          f"- Wells with long-run mean monsoon < {WELL_MONSOON_MIN_MM} mm: **{len(low_w)}**.",
          f"- Wells with long-run mean annual > {ANNUAL_MAX_MM} mm: **{int((wa > ANNUAL_MAX_MM).sum())}** "
          f"(max {wa.max():.0f} mm).",
          f"- Individual well-years with monsoon < {WELLYEAR_MONSOON_MIN_MM} mm: **{len(wy_low)}** "
          f"in {wy_low.well_id.nunique()} wells"
          + (f" ({', '.join(f'{k}: {v}' for k, v in wy_low.groupby(['state', 'year']).size().items())})"
             if len(wy_low) else "") + ".",
          f"- Months with exactly 0 mm: {int((full.precip_mm == 0).sum()):,} "
          f"({100 * (full.precip_mm == 0).mean():.1f}%), almost all in the dry season "
          f"({100 * full[full.precip_mm == 0].month.isin([11, 12, 1, 2, 3, 4]).mean():.0f}% in Nov-Apr)."]
    L += ["\n## 4. Interpretation of the flagged items (reviewed by hand)\n",
          "- **Low monsoon wells**: all are in Erode, Tiruppur and Coimbatore (Tamil Nadu), in the rain "
          "shadow of the Western Ghats. This region gets most of its rain from the north-east monsoon "
          "(Oct-Dec), so a low Jun-Sep total is expected. Their annual totals (~550-700 mm) are "
          "plausible. Implication: Jun-Sep features (`rain_last_monsoon_*`) carry less signal for "
          "Tamil Nadu, and the 12-month and monsoon-year-to-date features matter more there.",
          "- **Annual > 7,000 mm**: all are wells in Udupi (Karnataka) near the Western Ghats crest "
          "(around Agumbe, one of the wettest places in India), so the values are plausible.",
          "- **The single well-year with monsoon < 50 mm** is also in Tamil Nadu (2002, a drought year), "
          "consistent with the point above.",
          "- **Most-flagged well** (`We3954794ef`, Kanpur Dehat): the readings fall steadily from 8 m (2000) "
          "to 19 m (2022), while the recorded well depth is 14 m. Every later reading is therefore "
          "`deeper_than_well`. A smooth series like this points to a deepened well or an outdated depth "
          "record, not bad readings. `deeper_than_well` should be read mainly as a well-depth metadata "
          "problem.",
          "- **Near-duplicate locations**: 2 wells in Chanderi, Ashok Nagar (MP), ~100 m apart "
          "(`Chanderi` / `Chanderi(d)`) share the same CHIRPS cell. They are kept as separate wells."]
    (config.REPORTS_DIR / "data_validity.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
