"""Part E step 1: match the 2,759 wells in the stage-4 file, extract 2023-24
rounds, and report matching proof + coverage (before any features are built).

Run: python scripts/09a_extension_match.py
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import clean, config, extension, gw_io, reshape  # noqa: E402


def main() -> None:
    main_wide = gw_io.load_wide(config.GW_REFINED_FILE)
    kept, log = extension.match_stage4(main_wide)
    ext_cols = extension.extension_columns(kept)
    # Reuse the stage-2 reshape on a wide frame holding only the 2023-24 rounds,
    # with static covariates (incl. Reference_Sy) taken from the MAIN table so
    # they are identical to the main rows.
    meta, _, _ = gw_io.split_columns(main_wide.drop(columns="well_id"))
    wide = main_wide[["well_id"] + meta + ["Reference_Sy"]].merge(
        kept[["well_id"] + ext_cols], on="well_id", validate="one_to_one")
    long = reshape.to_long(wide)
    long, clog = clean.clean(long)          # same stage-3 rules; flag_extreme uses 2023-24 only here
    config.INTERIM_DIR.mkdir(parents=True, exist_ok=True)
    long.to_parquet(config.EXT_LONG, index=False)

    main_long = pd.read_parquet(config.GW_CLEAN)
    L = ["# Extension holdout 2023-2024\n", "_Generated by `scripts/09a_extension_match.py` "
         "(matching, coverage) and `scripts/09b_extension_features.py` (features)._\n",
         "**Read this first.** These rounds come from the authors' stage-4 file "
         "(`Output/4_India_GWLs_2000_2024_after_3sigma.csv`). The 2,759 wells were selected for "
         "completeness through 2022, so their 2023-2024 readings **did NOT pass the authors' "
         "repeated-value filter (criterion 5) or the >= 2 readings per year rule (criterion 4)**. "
         "They did pass the 3-sigma step (criterion 3), whose mean and std were computed over "
         "2000-2024. **Coverage is lower** than in the main table (see below). They are kept in "
         "`processed/extension_2023_2024/` and never mixed into the main table.\n",
         "## 1. Matching proof\n",
         f"- Stage-4 rows: {log['stage4_rows']:,}. Rows whose surrogate `well_id` is one of the "
         f"{log['main_wells']:,} main wells: {log['candidate_rows']:,}.",
         f"- **Unmatched main wells: {len(log['unmatched_main_wells'])}**.",
         f"- Wells with more than one stage-4 row: {len(log['ids_with_multiple_rows'])} "
         f"({', '.join(f'{k}: {v}' for k, v in log['multi_rows_resolved'].items()) or 'none'}). "
         "Resolved by taking the row whose 2000-2022 readings equal the main table; exactly one "
         "qualified. For `W0388be4a8d` (Raidih, Gumla, Jharkhand) the other row is a sparse twin "
         "(2 readings in 2000-2022, data from 2013). Its two 2023-24 readings are identical to the "
         "kept row's, so no information is lost.",
         f"- **Every matched well's 2000-2022 readings equal the main table exactly** "
         f"({len(main_wide):,} wells x 92 rounds, float tolerance 1e-8), so each match is the same series.",
         f"- **Coordinate mismatches: {log['coordinate_mismatches']}** (raw lat/lon compared, not just the hash).",
         f"- Stage-4 rows with the same state/district/station name as a main well but different "
         f"coordinates (not matched, reported only): {log['same_name_other_coords_rows']}.",
         "- Static covariates (well type, depth, aquifer, Reference_Sy) are taken from the main table.\n",
         "## 2. Coverage per round (% of 2,759 wells with a reading)\n"]
    cov_e = long.groupby(["period_label", "year", "month"]).gwl_m_bgl.agg(
        readings="count", pct=lambda s: round(100 * s.notna().mean(), 1)).reset_index().sort_values(["year", "month"])
    L.append(cov_e.drop(columns=["year", "month"]).to_markdown(index=False))
    m5 = main_long[main_long.year.between(2018, 2022)]
    cmp = pd.DataFrame({
        "2018-2022 mean %": m5.groupby("season", observed=True).gwl_m_bgl.apply(lambda s: 100 * s.notna().mean()),
        "2018-2022 min round %": m5.groupby(["season", "year"], observed=True).gwl_m_bgl
        .apply(lambda s: 100 * s.notna().mean()).groupby(level=0).min(),
        "2023-2024 mean %": long.groupby("season", observed=True).gwl_m_bgl.apply(lambda s: 100 * s.notna().mean())}).round(1)
    L += ["\n## 3. Missingness pattern vs 2018-2022\n", cmp.to_markdown(),
          f"\nOverall: 2018-2022 {100 * m5.gwl_m_bgl.notna().mean():.1f}% of cells have a reading; "
          f"2023-2024 {100 * long.gwl_m_bgl.notna().mean():.1f}%."]
    nw = long.groupby("well_id").gwl_m_bgl.count()
    L.append(f"\nReadings per well in 2023-24 (max 8): "
             + ", ".join(f"{k}: {v}" for k, v in nw.value_counts().sort_index().items())
             + f". Wells with none: **{int((nw == 0).sum())}**.")
    st = long.groupby("state").gwl_m_bgl.apply(lambda s: round(100 * s.notna().mean(), 1))
    st5 = m5.groupby("state").gwl_m_bgl.apply(lambda s: round(100 * s.notna().mean(), 1))
    L += ["\nBy state (% of cells with a reading):\n",
          pd.DataFrame({"2018-2022": st5, "2023-2024": st}).assign(change=lambda t: (t["2023-2024"] - t["2018-2022"]).round(1))
          .sort_values("change").to_markdown()]
    L.append(f"\nCleaning on extension rows: " + ", ".join(f"{k}={v}" for k, v in clog.items()
                                                          if not k.endswith('_names_changed')))
    z = long[long.flag_zero]
    L += [f"\n**Zero readings: {len(z)} in 2023-24 ({100 * len(z) / long.gwl_m_bgl.notna().sum():.2f}% of "
          f"readings) vs 11 in all of 2000-2022 (0.005%).** {int((z.period_label == 'May-23').sum())} are "
          "in May-23, the driest round, in wells whose 2020-22 median depth is about 4 m. They look like "
          "placeholders or 'dry' codes rather than water at the surface. Per the zero-reading decision "
          "they are kept and flagged (`flag_zero`, and `suspect_reason = zero_extension`), not set to "
          "NaN. **Recommend excluding them from any evaluation on this holdout.**"]
    (config.REPORTS_DIR / "extension_2023_2024.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
