"""Part F: write processed/splits.parquet and reports/splits_summary.md.
Cutoffs: config/splits.json.

Run: python scripts/10_splits.py
"""
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gwstress import config, splits  # noqa: E402

SPLITS_PATH = config.PROCESSED_DIR / "splits.parquet"


def main() -> None:
    cfg = splits.load_config()
    main_t = pd.read_parquet(config.FINAL_DIR)
    ext_p = config.EXT_DIR / "extension_features.parquet"
    ext = pd.read_parquet(ext_p) if ext_p.exists() else None
    s, cov = splits.build(main_t, ext, cfg)
    s.to_parquet(SPLITS_PATH, index=False)

    e = s[s.eval_eligible]
    sp = cov[cov.is_sparse].sort_values(["source", "period_label"])
    L = ["# Splits summary\n", "_Generated by `scripts/10_splits.py` from `config/splits.json`. "
         "File: `processed/splits.parquet`, keyed by (`well_id`, `period_label`)._\n",
         "## Rules\n",
         f"- `eval_eligible` = reading exists AND at least {cfg['K_min_history']} earlier same-season "
         "readings (baseline exists) AND round not sparse.",
         f"- Sparse round: coverage < {cfg['sparse_round_min_coverage_pct']}% of wells (2000-2022) or "
         f"< {cfg['ext_sparse_round_min_coverage_pct']}% (2023-2024 extension, whose coverage is low by "
         "construction).",
         "- `split_chrono`: " + ", ".join(f"{k} {v[0]}-{v[1]}" for k, v in cfg["chrono"].items()) + ".",
         "- `state_fold`: integer per state, alphabetical. `no_may_state`: well has no May reading 2000-2022.\n",
         "## Excluded sparse rounds\n",
         sp.assign(coverage_pct=sp.coverage_pct.round(1)).to_markdown(index=False),
         f"\n## Rows\n\nTotal {len(s):,} rows ({(s.source == 'main').sum():,} main + "
         f"{(s.source == 'extension').sum():,} extension); eval-eligible **{len(e):,}**.\n",
         "Exclusion reasons:\n", s.exclusion_reason.value_counts(dropna=False).rename(index=lambda v: "eligible" if pd.isna(v) else v)
         .to_frame("rows").to_markdown(),
         "\n## Eval-eligible rows per split and season\n",
         pd.crosstab(e.split_chrono, e.season, margins=True).reindex(
             ["train", "val", "test", "ext", "All"]).to_markdown(),
         "\n## Eval-eligible rows per state fold and split\n",
         pd.crosstab([e.state_fold, e.state], e.split_chrono).reindex(columns=["train", "val", "test", "ext"])
         .to_markdown(),
         f"\nWells with `no_may_state`: {s.drop_duplicates('well_id').no_may_state.sum()}."]
    (config.REPORTS_DIR / "splits_summary.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
